<a href="https://colab.research.google.com/github/sushantkumar143/Python-Toolbox-for-Data-Science/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
l = [[1,2,3], [4,5,6], [7,8,9]]
numpy_array = np.array(l)
print(numpy_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
zeros_array = np.zeros((3,4))
zeros_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
ones_array = np.ones((3,4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
random_array = np.random.rand(3,4)
print(random_array)

[[0.52043249 0.09386812 0.98952565 0.90806402]
 [0.18725276 0.85927577 0.14625811 0.50246649]
 [0.88552825 0.91448045 0.01102463 0.34481496]]


In [19]:
randn_array = np.random.randn(3,4)
print(randn_array)

[[ 0.04248613 -0.66881255 -0.3116735  -0.16582036]
 [-1.38881281  0.63069073  0.47339866 -0.85001077]
 [-0.4873969  -0.81484878  1.4672491   1.23925091]]


In [20]:
randint_array = np.random.randint(1,100,10)
print(randint_array)

[13 77 45 66 61 32 15  4 79  8]


In [37]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
#arr[0]
arr[-1][0]
arr[1,1]

5

In [28]:
print("Shape of Array", numpy_array.shape)

Shape of Array (3, 3)


In [32]:
a1 = np.array([[1,2,3], [4,5,6]])
print("Shape of Array", a1.shape)

Shape of Array (2, 3)


In [45]:
#a1 = a1.reshape(1,6)
a1 = a1.reshape(3,2)
#a1 = a1.reshape(-1)      ONE DIMENSIONAL ARRAY IS GENERATED
print(a1)
print("Shape of Array", a1.shape)

[[1 2]
 [3 4]
 [5 6]]
Shape of Array (3, 2)


In [46]:
a1 = np.array([[1,2,3,4,5,6]])
print("Before shape of Array: ", a1.shape)
a1 = a1.T
print("After shape of Array: ", a1.shape)
print(a1)

Before shape of Array:  (1, 6)
After shape of Array:  (6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [52]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8], [9,10], [11,12]])
print("Shape of Array 1: ",arr1.shape)
print("Shape of Array 2: ",arr2.shape)
#arr3 = np.matmul(arr1, arr2)
arr3 = arr1 @ arr2
print("Shape of Array 3: ",arr3.shape)

Shape of Array 1:  (2, 3)
Shape of Array 2:  (3, 2)
Shape of Array 3:  (2, 2)


Pandas is built on Numpy useful for manupilating the dataset.
1. Series
2. Dataset

In [54]:
import pandas as pd
type_house = pd.Series(['Loft', 'Villa', 'House', 'Apartment'])
#print(type_house)
type_house

0         Loft
1        Villa
2        House
3    Apartment
dtype: object

In [55]:
df = pd.DataFrame({'Price':[100000, 300000], 'date_construction':[1960,2010]})
df.head()

Price  date_construction
0  100000               1960
1  300000               2010

from matplotlib import pyplot as plt
_df_0['Price'].plot(kind='hist', bins=20, title='Price')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['date_construction'].plot(kind='hist', bins=20, title='date_construction')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2.plot(kind='scatter', x='Price', y='date_construction', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['Price']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'Price'}, axis=1)
              .sort_values('Price', ascending=True))
  xs = counted['Price']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_3.sort_values('Price', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('Price')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['date_construction']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'date_construction'}, axis=1)
              .sort_values('date_construction', ascending=True))
  xs = counted['date_construction']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_4.sort_values('date_construction', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('date_construction')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_5['Price'].plot(kind='line', figsize=(8, 4), title='Price')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_6['date_construction'].plot(kind='line', figsize=(8, 4), title='date_construction')
plt.gca().spines[['top', 'right']].set_visible(False)