<a href="https://colab.research.google.com/github/sushantkumar143/Python-Toolbox-for-Data-Science/blob/main/Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
l = [[1,2,3], [4,5,6], [7,8,9]]
numpy_array = np.array(l)
print(numpy_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
zeros_array = np.zeros((3,4))
zeros_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
ones_array = np.ones((3,4))
print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
random_array = np.random.rand(3,4)
print(random_array)

[[0.52043249 0.09386812 0.98952565 0.90806402]
 [0.18725276 0.85927577 0.14625811 0.50246649]
 [0.88552825 0.91448045 0.01102463 0.34481496]]


In [19]:
randn_array = np.random.randn(3,4)
print(randn_array)

[[ 0.04248613 -0.66881255 -0.3116735  -0.16582036]
 [-1.38881281  0.63069073  0.47339866 -0.85001077]
 [-0.4873969  -0.81484878  1.4672491   1.23925091]]


In [20]:
randint_array = np.random.randint(1,100,10)
print(randint_array)

[13 77 45 66 61 32 15  4 79  8]


In [37]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
#arr[0]
arr[-1][0]
arr[1,1]

5

In [28]:
print("Shape of Array", numpy_array.shape)

Shape of Array (3, 3)


In [32]:
a1 = np.array([[1,2,3], [4,5,6]])
print("Shape of Array", a1.shape)

Shape of Array (2, 3)


In [45]:
#a1 = a1.reshape(1,6)
a1 = a1.reshape(3,2)
#a1 = a1.reshape(-1)      ONE DIMENSIONAL ARRAY IS GENERATED
print(a1)
print("Shape of Array", a1.shape)

[[1 2]
 [3 4]
 [5 6]]
Shape of Array (3, 2)


In [46]:
a1 = np.array([[1,2,3,4,5,6]])
print("Before shape of Array: ", a1.shape)
a1 = a1.T
print("After shape of Array: ", a1.shape)
print(a1)

Before shape of Array:  (1, 6)
After shape of Array:  (6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [52]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[7,8], [9,10], [11,12]])
print("Shape of Array 1: ",arr1.shape)
print("Shape of Array 2: ",arr2.shape)
#arr3 = np.matmul(arr1, arr2)
arr3 = arr1 @ arr2
print("Shape of Array 3: ",arr3.shape)

Shape of Array 1:  (2, 3)
Shape of Array 2:  (3, 2)
Shape of Array 3:  (2, 2)


Pandas is built on Numpy useful for manupilating the dataset.
1. Series
2. Dataset